akundotdev_conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.articles.urls")),
    path("about/", include("apps.users.urls")),
    path("tools/", include("apps.tools.urls")),
    path("shop/", include("apps.shop.urls")),
    path("order/", include("apps.orders.urls")),
]

apps/shop/urls.py
from django.urls import path


from .views import ProductListView, ProductDetailView

urlpatterns = [
    path("", ProductListView.as_view(), name="products_list"),
    path("<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
]

apps/orders/models.py
from django.db import models
from django.core.mail import send_mail


from apps.shop.models import Product

# Create your models here.
class Order(models.Model):
    name = models.CharField(verbose_name="Customer Name", max_length=150)
    email = models.CharField(verbose_name="Customer Email", max_length=150)
    paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    product = models.ForeignKey(
        Product, related_name="order_item", on_delete=models.CASCADE
    )

    class Meta:
        ordering = ("-created_at",)
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return f"Order #{self.id}"

    def send_email(self):
        subject = "Order on Akun.dev"
        message = f"Dear {self.name}!\n\nThank you for ordering {self.product}.\nWe will contact you shortly!\n\nBest regards,\nAlmaz Kunpeissov"
        from_email = "hello@akun.dev"
        recipient_list = [self.email, "hello@akun.dev"]
        send_mail(
            subject=subject,
            message=message,
            from_email=from_email,
            recipient_list=recipient_list,
            fail_silently=True,
        )

apps/shop/models.py
from django.db import models
from django.urls import reverse

from apps.articles.models import Tag

# Create your models here.
class Product(models.Model):
    name = models.CharField(verbose_name="Product", max_length=150)
    abbr = models.CharField(verbose_name="Abbreviation", max_length=4)
    slug = models.SlugField(verbose_name="Slug", unique=True)
    description = models.CharField(verbose_name="Description", max_length=280)
    price = models.PositiveSmallIntegerField(verbose_name="Price")
    full_description = models.TextField(verbose_name="full_description")
    tags = models.ManyToManyField(Tag, verbose_name="Tags")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product_detail", args=[self.slug])

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Product"

apps/shop/views.py
from django.views.generic import ListView, DetailView


from apps.users.models import CustomUser
from .models import Product

# Create your views here.
class ProductListView(ListView):
    model = Product
    context_object_name = "products"
    template_name = "shop/products_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["main_author"] = CustomUser.objects.filter(main_user=True).first()
        return context


class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"
    template_name = "shop/product_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["main_author"] = CustomUser.objects.filter(main_user=True).first()
        return context

templates/shop/product_detail.html
{% extends "_base.html" %}
{% block title %}{{product.name}}{% endblock title %}
{% block main_content %}
    <section id="main" class="main">
        <div class="container">
            <div class="my-4">
                <h1 class="display-4">{{ product.name }}</h1>
                <p class="lead">{{ product.description }}</p>
                <hr class="">
                <div class="row">
                    <div class="col=12 col-sm-6 mb-3">
                        <div class="d-flex justify-content-center mb-2"> 
                            <div class="col rounded border border-dark">
                                <div class="embed-responsive embed-responsive-1by1">
                                    <div class="embed-responsive-item display-4 d-flex justify-content-center   ">
                                        <div class="align-self-center text-underline"><u>{{product.abbr}}</u></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 mb-3">
                        <p class="font-weight-bold">${{ product.price }}</p>
                        <p>{{ product.full_description|safe|linebreaksbr }}</p>
                        <form method="post" action="/order/">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_name">Your name</label>
                                <input class="form-control" type="text" name="name" maxlength="150" required="" id="id_name">
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email address</label>
                                <input class="form-control" type="email" name="email" maxlength="150" required="" id="id_email">
                            </div>
                            
                            <input type="hidden" name="product" maxlength="150" required="" id="id_product" value={{ product.pk }}>
                            <input class="btn btn-block btn-outline-dark" type="submit" value="Order Now">
                        </form>
                    </div>
                    <div  class="col-12 col-sm-6 mb-3">

                    </div>
                </div>
                <hr class="">
                {% for tag in product.tags.all %}
                    <a href="{{tag.get_absolute_url}}" class="text-muted">#{{tag.tag_name}}</a>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock main_content %}

templates/shop/products_list.html
{% extends "_base.html" %}

{% block title %}Shop of Python | {% endblock title %}
{% block main_content %}
    <section id="main" class="main">
        <div class="container">
            <div class="my-4">
                <h1 class="display-4">Shop of Python</h1>
                <p class="lead">Let's shop for some Python stuff, take your time.<p>
                <hr>
                {% include 'includes/list_product.html' %}
            </div>
        </div>
    </section>
{% endblock main_content %}